module.exports = [
  [ { value: '2014', formatCode: '@' },
    { value: '珠宝系', formatCode: '@' },
    { value: '全日制2014宝玉石鉴定与加工技术(珠宝首饰制作工艺)J1班', formatCode: '@' },
    { value: '201400884', formatCode: '@' },
    { value: '黄艺菲', formatCode: '@' },
    { value: '在读', formatCode: '@' } ],
  [ { value: '2014', formatCode: '@' },
    { value: '珠宝系', formatCode: '@' },
    { value: '全日制2014宝玉石鉴定与加工技术(珠宝首饰制作工艺)J1班', formatCode: '@' },
    { value: '201400885', formatCode: '@' },
    { value: '张惠君', formatCode: '@' },
    { value: '在读', formatCode: '@' } ],
  [ { value: '2014', formatCode: '@' },
    { value: '珠宝系', formatCode: '@' },
    { value: '全日制2014宝玉石鉴定与加工技术(珠宝首饰制作工艺)J1班', formatCode: '@' },
    { value: '201400886', formatCode: '@' },
    { value: '杨晶晶', formatCode: '@' },
    { value: '在读', formatCode: '@' } ],
  [ { value: '2014', formatCode: '@' },
    { value: '珠宝系', formatCode: '@' },
    { value: '全日制2014珠宝首饰工艺及鉴定J3班', formatCode: '@' },
    { value: '201401212', formatCode: '@' },
    { value: '刘紫筠', formatCode: '@' },
    { value: '在读', formatCode: '@' } ],
  [ { value: '2014', formatCode: '@' },
    { value: '珠宝系', formatCode: '@' },
    { value: '全日制2014珠宝首饰工艺及鉴定J4班', formatCode: '@' },
    { value: '201400798', formatCode: '@' },
    { value: '侯诗敏', formatCode: '@' },
    { value: '在读', formatCode: '@' } ],
  [ { value: '2014', formatCode: '@' },
    { value: '珠宝系', formatCode: '@' },
    { value: '全日制2014珠宝首饰工艺及鉴定J4班', formatCode: '@' },
    { value: '201401218', formatCode: '@' },
    { value: '赖烨', formatCode: '@' },
    { value: '在读', formatCode: '@' } ],
  [ { value: '2014', formatCode: '@' },
    { value: '珠宝系', formatCode: '@' },
    { value: '全日制2014珠宝首饰工艺及鉴定J4班', formatCode: '@' },
    { value: '201401297', formatCode: '@' },
    { value: '胡伟俊', formatCode: '@' },
    { value: '在读', formatCode: '@' } ] ]
